# Generated by Django 5.0.7 on 2024-08-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='created_by',
        ),
    ]
